name: Build Kernel Ginkgo OC KSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential flex gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi git libssl-dev libncurses5-dev python3 zip curl

      - name: Download Clang (Proton)
        run: |
          mkdir clang
          cd clang
          curl -LO https://github.com/kdrag0n/proton-clang/archive/refs/heads/master.tar.gz
          tar -xf master.tar.gz --strip-components=1

      - name: Download Kernel Source
        run: |
          git clone --depth=1 https://github.com/NetherKernel/android_kernel_xiaomi_ginkgo.git -b 10 kernel-src

      - name: Setup KernelSU
        run: |
          cd kernel-src
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Build Kernel
        run: |
          export PATH=$(pwd)/clang/bin:$PATH
          cd kernel-src
          make O=out ARCH=arm64 ginkgo_defconfig
          make -j$(nproc --all) O=out \
                      ARCH=arm64 \
                      CC=clang \
                      AR=llvm-ar \
                      NM=llvm-nm \
                      OBJCOPY=llvm-objcopy \
                      OBJDUMP=llvm-objdump \
                      STRIP=llvm-strip \
                      CLANG_TRIPLE=aarch64-linux-gnu- \
                      CROSS_COMPILE=aarch64-linux-gnu- \
                      CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Packing
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3 AnyKernel3
          find kernel-src/out/arch/arm64/boot/ -name "Image*" -exec cp {} AnyKernel3/ \;
          cd AnyKernel3
          zip -r9 ../Kernel-Ginkgo-Shadow-KSU.zip * -x .git README.md

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Shadow-RedmiNote8
          path: Kernel-Ginkgo-Shadow-KSU.zip
          
