name: Redmi Note 8 Kernel PRO Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update

        sudo apt install -y \
        bc bison build-essential curl flex git \
        libssl-dev make zip python3 wget \
        libelf-dev

    - name: Download Clang
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

    - name: Install KernelSU
      run: |
        curl -LSs https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh | bash -

    - name: Enable KernelSU + Performance
      run: |

        echo "CONFIG_KSU=y" >> arch/arm64/configs/vendor/ginkgo-perf_defconfig
        echo "CONFIG_LTO_CLANG=y" >> arch/arm64/configs/vendor/ginkgo-perf_defconfig
        echo "CONFIG_THINLTO=y" >> arch/arm64/configs/vendor/ginkgo-perf_defconfig

        echo "CONFIG_CPU_FREQ_GOV_PERFORMANCE=y" >> arch/arm64/configs/vendor/ginkgo-perf_defconfig
        echo "CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE=y" >> arch/arm64/configs/vendor/ginkgo-perf_defconfig

    - name: Build Kernel

      run: |

        export ARCH=arm64
        export SUBARCH=arm64

        export PATH=$PWD/clang/bin:$PATH

        export CC=clang
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export CROSS_COMPILE=aarch64-linux-android-
        export CROSS_COMPILE_ARM32=arm-linux-androideabi-

        make O=out vendor/ginkgo-perf_defconfig

        make -j8 O=out \
        CC=clang \
        CROSS_COMPILE=aarch64-linux-android-

    - name: Make Flashable Zip
      run: |

        git clone https://github.com/osm0sis/AnyKernel3

        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/

        cd AnyKernel3

        sed -i 's/device.name1=.*/device.name1=ginkgo/' anykernel.sh
        sed -i 's/device.name2=.*/device.name2=ginkgo/' anykernel.sh

        zip -r9 Kernel-Ginkgo-PRO-KSU.zip *

    - name: Upload Kernel

      uses: actions/upload-artifact@v4

      with:
        name: Ginkgo-Kernel

        path: AnyKernel3/Kernel-Ginkgo-PRO-KSU.zip
        
